"use client";

import { Space_Grotesk } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "aos/dist/aos.css";
import "@/public/style/swiper/swiper-bundle.min.css";
import "@/public/assets/font/font-awesome.css";
import "@/public/assets/font/risebot.css";
import "@/public/style/dist/app.css";

import { Providers } from "./providers";

// ✅ Export metadata correctly for Next.js App Router
export const metadata = {
  title: "Risebot - Metaverse Web3 IGO Launchpad Next.js Template",
  description: "Generated by create next app",
};

// ✅ Load Google Font with multiple weights
const grotesk = Space_Grotesk({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--grotesk",
  display: "swap",
});

// ✅ Root Layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${grotesk.variable} header-fixed page-loaded`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
